version: "3"
services:
  lab:
    build: ./img
    ports:
      - 6666:6666
      - 6667:6667
      - 6668:6668
      - 6669:6669
      - 6670:6670
    volumes:
      - '.:/home/stu/devlop'
    cap_add:
      - ALL
    privileged: true
    working_dir: '/home/stu/devlop'